# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name=b'project',
        ),
        migrations.RemoveField(
            model_name='interface',
            name=b'project',
        ),
        migrations.RemoveField(
            model_name='plan',
            name=b'environment',
        ),
        migrations.RemoveField(
            model_name='plan',
            name=b'project',
        ),
        migrations.RemoveField(
            model_name='report',
            name=b'plan',
        ),
        migrations.RemoveField(
            model_name='case',
            name=b'content',
        ),
        migrations.RemoveField(
            model_name='case',
            name=b'description',
        ),
        migrations.RemoveField(
            model_name='project',
            name=b'sign',
        ),
        migrations.AddField(
            model_name='case',
            name='case_content',
            field=models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_creator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8bbe\u8ba1\u4eba'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_executor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6267\u884c\u4eba'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_expect',
            field=models.TextField(blank=True, null=True, verbose_name='\u671f\u671b\u7ed3\u679c'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_func',
            field=models.TextField(blank=True, null=True, verbose_name='\u64cd\u4f5c\u6b65\u9aa4'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u4f18\u5148\u7ea7'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_pre',
            field=models.TextField(blank=True, null=True, verbose_name='\u524d\u7f6e\u6761\u4ef6'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_result',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6d4b\u8bd5\u7ed3\u679c'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6267\u884c\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6d4b\u8bd5\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='case',
            name=b'case_name',
            field=models.CharField(max_length=100, verbose_name='\u7528\u4f8b\u6807\u9898'),
        ),
        migrations.DeleteModel(
            name='Environment',
        ),
        migrations.DeleteModel(
            name='Interface',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Sign',
        ),
    ]
