# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20181010_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name=b'project',
        ),
    ]
