# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20181011_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4f18\u5148\u7ea7'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_result',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6d4b\u8bd5\u7ed3\u679c'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6267\u884c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6d4b\u8bd5\u7c7b\u578b'),
        ),
    ]
