# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20181016_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Project'),
        ),
    ]
