# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20181016_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u987a\u5e8f'),
        ),
    ]
