# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_case_case_locat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='case_locat',
            new_name='case_locate',
        ),
    ]
